name: Check if docker compiles

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: codenotary/immudb-docs
          path: immudb-docs
      - name: Build
        run: docker build immdub-docs
